title: Lifeclue
email: lifecluee@gmail.com
description: "Developer / Backend / Java / Spring / Kotlin / Ktor"
show_downloads: false
show_excerpts: true
markdown: kramdown
google_analytics: UA-42372652-1
baseurl: "/blog"
date_format: "%F"

# https://github.com/dirkfabisch/mediator
name: "Lifeclue"
author: "Lifeclue"
paginate: 5
url: "https://lifeclue.github.io"
float_logo: "/assets/images/site/logo-32.png" # Cambria Math
logo: "/assets/images/site/author_image.jpg"
cover: "/assets/images/site/cover.svg"
author_image: "/assets/images/site/author_image.jpg"
disqus: "lifeclue-blog"

social:
  - icon:	github
    url:	https://github.com/lifeclue
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate
#- jekyll-coffeescript
#- jekyll-gist
#- jekyll-github-metadata
#- jekyll-paginate
#- jekyll-relative-links
#- jekyll-optional-front-matter
#- jekyll-readme-index
#- jekyll-default-layout
#- jekyll-titles-from-headings
#- jekyll-toc
#- jekyll-remote-theme


