title: Lifeclue
email: lifecluee@gmail.com
description: "Lifeclue라는 필명으로 글을 써나가고 있습니다. 주로 개발과 관련된 이야기  를 씁니다." # used by search engines
github_username: lifeclue
repository: blog/lifeclue
show_downloads: false
markdown: kramdown
google_analytics: UA-42372652-1
theme: jekyll-theme-slate
baseurl: "/blog"

plugins:
- jekyll-coffeescript
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-toc
